In [2]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,LabelEncoder
import pickle

In [3]:
data = pd.read_csv("Churn_Modelling.csv")

In [4]:
data.head(3)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1

In [5]:
##Dropping irrelevant columns
data = data.drop(['RowNumber','CustomerId','Surname'],axis=1)
data.head(2)

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0

In [6]:
##Encoding categorical variables

In [7]:
##Label Encoder
label_encoder_gender = LabelEncoder()
data['Gender'] = label_encoder_gender.fit_transform(data['Gender'])
data.head(3)

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,0,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0
2,502,France,0,42,8,159660.80,3,1,0,113931.57,1

In [8]:
data['Geography'].unique()

<ArrowStringArray>
['France', 'Spain', 'Germany']
Length: 3, dtype: str

In [9]:
##OnehotEncoding

from sklearn.preprocessing import OneHotEncoder
OneHot_encoder_geo = OneHotEncoder()
geo_encoder = OneHot_encoder_geo.fit_transform(data[['Geography']]).toarray()
geo_encoder

array([[1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       ...,
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [10]:
OneHot_encoder_geo.get_feature_names_out(['Geography'])

array(['Geography_France', 'Geography_Germany', 'Geography_Spain'],
      dtype=object)

In [11]:
geo_encoded_df = pd.DataFrame(geo_encoder,columns=OneHot_encoder_geo.get_feature_names_out(['Geography']))

In [12]:
geo_encoded_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [13]:
data = pd.concat([data.drop('Geography',axis=1),geo_encoded_df],axis=1)

In [14]:
data

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771,1,39,5,0.00,2,1,0,96270.64,0,1.0,0.0,0.0
9996,516,1,35,10,57369.61,1,1,1,101699.77,0,1.0,0.0,0.0
9997,709,0,36,7,0.00,1,0,1,42085.58,1,1.0,0.0,0.0
9998,772,1,42,3,75075.31,2,1,0,92888.52,1,0.0,1.0,0.0
9999,792,0,28,4,130142.79,1,1,0,38190.78,0,1.0,0.0,0.0

In [15]:
## Save the pickle files

with open('label_encoder_gender.pkl','wb') as file:
    pickle.dump(label_encoder_gender,file)

with open('OneHot_encoder_geo.pkl','wb') as file:
    pickle.dump(OneHot_encoder_geo,file)

In [16]:
data.head(3)

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0

In [17]:
##Dividing dataset into dependent and independent features
X = data.drop('Exited',axis=1)
y = data['Exited']

In [18]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [19]:
X_train.shape

(8000, 12)

In [20]:
X_test.shape

(2000, 12)

In [21]:
y_train.shape

(8000,)

In [22]:
y_test.shape

(2000,)

In [23]:
##Feature Scaling
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [24]:
X_train

array([[ 0.35649971,  0.91324755, -0.6557859 , ...,  1.00150113,
        -0.57946723, -0.57638802],
       [-0.20389777,  0.91324755,  0.29493847, ..., -0.99850112,
         1.72572313, -0.57638802],
       [-0.96147213,  0.91324755, -1.41636539, ..., -0.99850112,
        -0.57946723,  1.73494238],
       ...,
       [ 0.86500853, -1.09499335, -0.08535128, ...,  1.00150113,
        -0.57946723, -0.57638802],
       [ 0.15932282,  0.91324755,  0.3900109 , ...,  1.00150113,
        -0.57946723, -0.57638802],
       [ 0.47065475,  0.91324755,  1.15059039, ..., -0.99850112,
         1.72572313, -0.57638802]])

In [25]:
scaler

StandardScaler()

In [26]:
with open('scaler.pkl','wb') as file:
    pickle.dump(scaler,file)

In [27]:
data

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771,1,39,5,0.00,2,1,0,96270.64,0,1.0,0.0,0.0
9996,516,1,35,10,57369.61,1,1,1,101699.77,0,1.0,0.0,0.0
9997,709,0,36,7,0.00,1,0,1,42085.58,1,1.0,0.0,0.0
9998,772,1,42,3,75075.31,2,1,0,92888.52,1,0.0,1.0,0.0
9999,792,0,28,4,130142.79,1,1,0,38190.78,0,1.0,0.0,0.0

In [28]:
X_train

array([[ 0.35649971,  0.91324755, -0.6557859 , ...,  1.00150113,
        -0.57946723, -0.57638802],
       [-0.20389777,  0.91324755,  0.29493847, ..., -0.99850112,
         1.72572313, -0.57638802],
       [-0.96147213,  0.91324755, -1.41636539, ..., -0.99850112,
        -0.57946723,  1.73494238],
       ...,
       [ 0.86500853, -1.09499335, -0.08535128, ...,  1.00150113,
        -0.57946723, -0.57638802],
       [ 0.15932282,  0.91324755,  0.3900109 , ...,  1.00150113,
        -0.57946723, -0.57638802],
       [ 0.47065475,  0.91324755,  1.15059039, ..., -0.99850112,
         1.72572313, -0.57638802]])

In [29]:
X_test

array([[-0.57749609,  0.91324755, -0.6557859 , ..., -0.99850112,
         1.72572313, -0.57638802],
       [-0.29729735,  0.91324755,  0.3900109 , ...,  1.00150113,
        -0.57946723, -0.57638802],
       [-0.52560743, -1.09499335,  0.48508334, ..., -0.99850112,
        -0.57946723,  1.73494238],
       ...,
       [ 0.81311987, -1.09499335,  0.77030065, ...,  1.00150113,
        -0.57946723, -0.57638802],
       [ 0.41876609,  0.91324755, -0.94100321, ...,  1.00150113,
        -0.57946723, -0.57638802],
       [-0.24540869,  0.91324755,  0.00972116, ..., -0.99850112,
         1.72572313, -0.57638802]])

In [30]:
y_train

9254    0
1561    0
1670    1
6087    1
6669    1
       ..
5734    0
5191    0
5390    1
860     1
7270    0
Name: Exited, Length: 8000, dtype: int64

In [31]:
y_test

6252    0
4684    0
1731    0
4742    0
4521    0
       ..
6412    1
8285    0
7853    1
1095    1
6929    1
Name: Exited, Length: 2000, dtype: int64

In [32]:
### ANN implementation

In [33]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard
import datetime

WARNING:tensorflow:From d:\DS\GenAI_projects\ANN_project_implementation\venv\Lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

In [34]:
(X_train.shape[1],)

(12,)

In [35]:
##Building ANN model

model = Sequential(
    [
    Dense(64,activation='relu',input_shape = (X_train.shape[1],)),
    Dense(32,activation='relu'),
    Dense(1,activation='sigmoid') 
    ]
    )

WARNING:tensorflow:From d:\DS\GenAI_projects\ANN_project_implementation\venv\Lib\site-packages\keras\src\backend.py:873: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

In [36]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 64)                832

 dense_1 (Dense)             (None, 32)                2080

 dense_2 (Dense)             (None, 1)                 33

=================================================================
Total params: 2945 (11.50 KB)
Trainable params: 2945 (11.50 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [37]:
import tensorflow
opt = tensorflow.keras.optimizers.Adam(learning_rate=0.01)
loss = tensorflow.keras.losses.BinaryCrossentropy()
loss

In [38]:
##Compiling model
model.compile(optimizer=opt,loss='binary_crossentropy',metrics=['accuracy'])

In [39]:
## Set up the Tensorboard

from tensorflow.keras.callbacks import EarlyStopping,TensorBoard

log_dir = "logs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")

In [40]:
tensorflow_callback = TensorBoard(log_dir=log_dir,histogram_freq=1)

In [41]:
early_stopping_callback = EarlyStopping(monitor='val_loss',patience=10,restore_best_weights=True)

In [44]:
history = model.fit(
    X_train,y_train,validation_data = (X_test,y_test),epochs=100,
    callbacks = [tensorflow_callback,early_stopping_callback]
)

Epoch 1/100
WARNING:tensorflow:From d:\DS\GenAI_projects\ANN_project_implementation\venv\Lib\site-packages\keras\src\utils\tf_utils.py:492: The name tf.ragged.RaggedTensorValue is deprecated. Please use tf.compat.v1.ragged.RaggedTensorValue instead.

WARNING:tensorflow:From d:\DS\GenAI_projects\ANN_project_implementation\venv\Lib\site-packages\keras\src\engine\base_layer_utils.py:384: The name tf.executing_eagerly_outside_functions is deprecated. Please use tf.compat.v1.executing_eagerly_outside_functions instead.

250/250 [==============================] - 2s 4ms/step - loss: 0.3983 - accuracy: 0.8335 - val_loss: 0.3540 - val_accuracy: 0.8595
Epoch 2/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3542 - accuracy: 0.8554 - val_loss: 0.3527 - val_accuracy: 0.8540
Epoch 3/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3493 - accuracy: 0.8546 - val_loss: 0.3464 - val_accuracy: 0.8555
Epoch 4/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3425 - accuracy: 0.8586 - val_loss: 0.3459 - val_accuracy: 0.8625
Epoch 5/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3400 - accuracy: 0.8584 - val_loss: 0.3465 - val_accuracy: 0.8590
Epoch 6/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3396 - accuracy: 0.8606 - val_loss: 0.3444 - val_accuracy: 0.8595
Epoch 7/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3335 - accuracy: 0.8610 - val_loss: 0.3398 - val_accuracy: 0.8605
Epoch 8/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3329 - accuracy: 0.8602 - val_loss: 0.3439 - val_accuracy: 0.8570
Epoch 9/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3321 - accuracy: 0.8652 - val_loss: 0.3487 - val_accuracy: 0.8570
Epoch 10/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3299 - accuracy: 0.8648 - val_loss: 0.3462 - val_accuracy: 0.8625
Epoch 11/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3293 - accuracy: 0.8634 - val_loss: 0.3549 - val_accuracy: 0.8605
Epoch 12/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3277 - accuracy: 0.8637 - val_loss: 0.3424 - val_accuracy: 0.8625
Epoch 13/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3245 - accuracy: 0.8664 - val_loss: 0.3453 - val_accuracy: 0.8630
Epoch 14/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3206 - accuracy: 0.8690 - val_loss: 0.3473 - val_accuracy: 0.8650
Epoch 15/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3227 - accuracy: 0.8646 - val_loss: 0.3454 - val_accuracy: 0.8625
Epoch 16/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3185 - accuracy: 0.8666 - val_loss: 0.3469 - val_accuracy: 0.8600
Epoch 17/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3168 - accuracy: 0.8673 - val_loss: 0.3537 - val_accuracy: 0.8595

In [45]:
model.save('model.h5')

d:\DS\GenAI_projects\ANN_project_implementation\venv\Lib\site-packages\keras\src\engine\training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(

In [4]:
%reload_ext tensorboard

In [5]:
%tensorboard --logdir logs/fit

Reusing TensorBoard on port 6006 (pid 23596), started 0:01:17 ago. (Use '!kill 23596' to kill it.)

In [4]:
pip install setuptools==80.9.0

Collecting setuptools==80.9.0
  Downloading setuptools-80.9.0-py3-none-any.whl.metadata (6.6 kB)
Downloading setuptools-80.9.0-py3-none-any.whl (1.2 MB)
   ---------------------------------------- 0.0/1.2 MB ? eta -:--:--
   ---------------------------------- ----- 1.0/1.2 MB 12.7 MB/s eta 0:00:01
   ---------------------------------------- 1.2/1.2 MB 5.5 MB/s  0:00:00
Installing collected packages: setuptools
  Attempting uninstall: setuptools
    Found existing installation: setuptools 84.0.0
    Uninstalling setuptools-84.0.0:
      Successfully uninstalled setuptools-84.0.0
Successfully installed setuptools-80.9.0
Note: you may need to restart the kernel to use updated packages.