In [2]:
import numpy  as np
import pandas as pd
import tensorflow as tf
import pickle
from tensorflow.keras.models import load_model

In [3]:
model = load_model('model.h5')

WARNING:tensorflow:From d:\DS\GenAI_projects\ANN_project_implementation\venv\Lib\site-packages\keras\src\backend.py:1398: The name tf.executing_eagerly_outside_functions is deprecated. Please use tf.compat.v1.executing_eagerly_outside_functions instead.

In [ ]:
## Reading label encoded gender
with open("label_encoder_gender.pkl",'rb') as file:
    label_encoder_gender = pickle.load(file)

In [ ]:
## Reading Onehot encoed geo

with open("OneHot_encoder_geo.pkl",'rb') as file:
    label_encoder_geo = pickle.load(file)

In [8]:
## Reading scaler 
with open("scaler.pkl",'rb') as file:
    scaler = pickle.load(file)

In [10]:
# Example input data
input_data = {
    'CreditScore': 600,
    'Geography': 'France',
    'Gender': 'Male',
    'Age': 40,
    'Tenure': 3,
    'Balance': 60000,
    'NumOfProducts': 2,
    'HasCrCard': 1,
    'IsActiveMember': 1,
    'EstimatedSalary': 50000
}

In [13]:
label_encoder_geo.get_feature_names_out()

array(['Geography_France', 'Geography_Germany', 'Geography_Spain'],
      dtype=object)

In [18]:
## One hot encoded geography

geo_encoded = label_encoder_geo.transform([[input_data['Geography']]]).toarray()

d:\DS\GenAI_projects\ANN_project_implementation\venv\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

In [24]:
geo_encoded_df = pd.DataFrame(geo_encoded,columns=label_encoder_geo.get_feature_names_out(['Geography']))

In [25]:
geo_encoded_df

   Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0

In [30]:
input_df = pd.DataFrame([input_data])

In [32]:
input_df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,600,France,Male,40,3,60000,2,1,1,50000

In [34]:
input_df['Gender'] = label_encoder_gender.transform(input_df['Gender'])

In [39]:
input_df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,600,France,1,40,3,60000,2,1,1,50000

In [42]:
##Concatenate one hot encoded dataframe

input_df = pd.concat([input_df.drop('Geography',axis=1),geo_encoded_df],axis=1)

In [43]:
input_df

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain
0,600,1,40,3,60000,2,1,1,50000,1.0,0.0,0.0

In [44]:
input_scaled = scaler.transform(input_df)

In [45]:
input_scaled

array([[-0.53598516,  0.91324755,  0.10479359, -0.69539349, -0.25781119,
         0.80843615,  0.64920267,  0.97481699, -0.87683221,  1.00150113,
        -0.57946723, -0.57638802]])

In [51]:
prediction = model.predict(input_scaled)
prediction

1/1 [==============================] - 0s 23ms/step

array([[0.03020819]], dtype=float32)

In [56]:
prediction_proba = prediction[0][0]

In [57]:
prediction_proba

0.030208195

In [58]:
if prediction_proba > 0.5:
    print('The customer is likely to churn.')
else:
    print('The customer is not likely to churn.')

The customer is not likely to churn.